[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "/app/start.sh"
healthcheckPath = ""
healthcheckTimeout = 0
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10